---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "IngeNUity 2017"
keywords:    "Ingenuity, Techno Fest, NIIT University, Fest, Cultural-fest"
description: "Ingenuity Techo-Cultural Fest"
bg-img: ""
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#FAFAFA'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

collections:
  events:
    output: true
    permalink: /:path

kramdown:
  auto_ids:  false

